blog/urls.py
from django.urls import path, include
from . import views
from . import api
from .api import PostModelViewSet
from rest_framework.routers import DefaultRouter
from django.views.generic import TemplateView


app_name = "blog"

router = DefaultRouter()
router.register(prefix="posts", viewset=PostModelViewSet)


urlpatterns = [
    # path("", TemplateView.as_view(template_name="blog/index.html"), name="index"),
    path("", views.index, name="index"),
    path("whoami/", views.whoami, name="whoami"),
]
urlpatterns_api_v1 = []
urlpatterns_api_v1 += router.urls

# urlpatterns_api_v1 = [
#     path("", api.post_list, name="post_list"),
#     path("<int:pk>/", api.post_detail, name="post_detail"),
#     path("new/", api.post_list, name="post_new"),
#     path("<int:pk>/edit/", api.post_detail, name="post_edit"),
#     path("<int:pk>/delete/", api.post_detail, name="post_delete"),
# ]

urlpatterns += [path("api/", include((urlpatterns_api_v1, "api-v1")))]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static

from django_nextjs.render import render_nextjs_page


# asgi에서는 async 지원
async def root(request):
    return await render_nextjs_page(request)


urlpatterns = [
    path("", root),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("blog/", include("blog.urls")),
    path("", include("photolog.urls")),
    path("", include("core.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if apps.is_installed("debug_toolbar"):
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

photolog/urls.py
from django.urls import path
from . import views


app_name = "photolog"

urlpatterns = [
    path("", views.index, name="index"),
    path("@<str:username>/", views.user_page, name="user_page"),
    path("@<str:username>/follow/", views.user_follow, name="user_follow"),
    path("user/following/", views.following_list, name="following_list"),
    path("user/discover/", views.discover_list, name="discover_list"),
    path("new/", views.NoteCreateView.as_view(), name="note_new"),
    path("<int:pk>/", views.NoteDetailView.as_view(), name="note_detail"),
    path("<int:pk>/edit/", views.note_edit, name="note_edit"),
    path(
        "<int:note_pk>/comments/", views.CommentListView.as_view(), name="comment_list"
    ),
    path(
        "<int:note_pk>/comment/new/",
        views.CommentCreateView.as_view(),
        name="comment_new",
    ),
    path(
        "<int:note_pk>/comment/<int:pk>/edit/",
        views.CommentUpdateView.as_view(),
        name="comment_edit",
    ),
    path(
        "<int:note_pk>/comment/<int:pk>/delete/",
        views.CommentDeleteView.as_view(),
        name="comment_delete",
    ),
]

photolog/models.py
from io import BytesIO
import re
from os.path import splitext
from typing import List
from uuid import uuid4
from django_lifecycle import LifecycleModelMixin, hook, BEFORE_SAVE, AFTER_SAVE
from PIL import Image
from taggit.managers import TaggableManager

from django.core.files import File
from django.core.files.base import ContentFile

from django.db import models
from django.utils import timezone
from django.utils.encoding import force_str
from django.urls import reverse_lazy

from accounts.models import User


class Note(LifecycleModelMixin, models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tags = TaggableManager()

    @hook(AFTER_SAVE, when="content", has_changed=True)
    def on_content_saved(self):
        hashtags: List[str] = re.findall(r"#(\w+)", self.content)
        self.tags.set(hashtags, clear=True)

    class Meta:
        ordering = ["-pk"]

    def get_absolute_url(self):
        return reverse_lazy("photolog:note_detail", kwargs={"pk": self.pk})


def uuid_name_upload_to(instance: models.Model, filename: str) -> str:
    app_label = instance.__class__._meta.app_label
    cls_name = instance.__class__.__name__.lower()
    ymd_path = force_str(timezone.now().strftime("%Y/%m/%d"))
    extension = splitext(filename)[-1].lower()
    new_filename = uuid4().hex + extension
    return "/".join((app_label, cls_name, ymd_path, new_filename))


class Photo(LifecycleModelMixin, models.Model):
    note = models.ForeignKey(Note, on_delete=models.CASCADE)
    image = models.ImageField(
        # upload_to="photolog/photo/%Y/%m/%d"
        upload_to=uuid_name_upload_to
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # List[File]를 저장하는 로직
    @classmethod
    def create_photos(cls, note: Note, photo_file_list: List[File]):
        if not note.pk:
            raise ValueError("cannot find note :<")

        photo_list = []
        for photo_file in photo_file_list:
            # note=note인 Photo 인스턴스 생성
            photo = cls(note=note)
            photo.image.save(photo_file.name, photo_file, save=False)
            photo_list.append(photo)

        cls.objects.bulk_create(photo_list)

        return photo_list

    # 이미지 변환 로직을 별도 함수로 분리
    @classmethod
    def make_thumb(
        cls,
        image_file: File,
        max_width: int = 1024,
        max_height: int = 1204,
        quality: int = 80,
    ) -> File:
        pil_image = Image.open(image_file)
        max_size = (max_width, max_height)
        pil_image.thumbnail(max_size)
        if pil_image.mode == "RGBA":
            pil_image = pil_image.convert("RGB")

        thumb_name = splitext(image_file.name)[0] + ".jpg"
        thumb_file = ContentFile(b"", name=thumb_name)
        pil_image.save(thumb_file, format="jpeg", quality=quality)

        return thumb_file

    # BEFORE_UPDATE: 기존 레코드를 수정해서 저장할 때 호출
    # BEFORE_CREATE: 새 레코드를 생성해서 저장할 때 호출
    # BEFORE_SAVE: 레코드 생성/수정 시 저장할 때 호출
    @hook(BEFORE_SAVE, when="image", has_changed=True)
    def on_image_changed(self):
        if self.image:
            image_width = self.image.width  # 이미지 가로
            image_extension = splitext(self.image.name)[-1].lower()  # 확장자명

            if image_width > 1024 or image_extension not in (".jpg", "jpeg"):
                thumb_file = self.make_thumb(self.image.file, 1024, 1024, 80)
                self.image.save(thumb_file.name, thumb_file, save=False)


class Comment(models.Model):
    note = models.ForeignKey(Note, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-pk"]

photolog/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.query import QuerySet
from django.forms import BaseModelForm
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import (
    CreateView,
    DetailView,
    UpdateView,
    ListView,
    DeleteView,
)
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django_htmx.http import trigger_client_event, HttpResponseClientRedirect
from core.decorators import login_required_hx
from django.utils.decorators import method_decorator

from .models import Note, Photo, Comment
from accounts.models import User
from .forms import NoteCreateForm, PhotoUpdateFormSet, NoteUpdateForm, CommentForm


def index(request):
    tag_name = request.GET.get("tag", "").strip()
    query = request.GET.get("query", "").strip()
    if tag_name:
        qs = Note.objects.filter(tags__name__in=[tag_name])

    elif query:
        qs = Note.objects.filter(Q(title__icontains=query) | Q(author__username=query))

    else:
        if not request.user.is_authenticated:
            qs = Note.objects.all()

        else:
            user = request.user
            qs = Note.objects.filter(
                Q(author__in=user.following_set.all()) | Q(author=user)
            )

    qs = qs.select_related("author").prefetch_related("photo_set", "tags")

    return render(request, "photolog/index.html", {"note_list": qs, "query": query})


def user_page(request, username):
    author = get_object_or_404(User, is_active=True, username=username)

    qs = Note.objects.filter(author=author)
    qs = qs.select_related("author").prefetch_related("photo_set", "tags")

    return render(
        request, "photolog/user_page.html", {"note_list": qs, "author": author}
    )


def user_follow(request, username: str):
    from_user = request.user
    to_user = get_object_or_404(User, username=username, is_active=True)

    # 1. method GET or POST
    # 2. user.is_authenticated
    # 3. is_follower

    # GET일 경우에는 단순 팔로잉 버튼 렌더링
    if request.method == "GET":
        if from_user.is_authenticated:
            is_follower = from_user.is_follower(to_user)
        else:
            is_follower = False
    else:
        if from_user.is_authenticated:
            # 이미 팔로우 되있는 지 확인 여부에 따라 다른 로직 수행
            is_follower = from_user.is_follower(to_user)

            from_user.follow(to_user)
            print("전", is_follower)
            is_follower = not is_follower
            print("후", is_follower)
        else:
            current_uri = request.META.get("HTTP_HX_CURRENT_URL")
            redirect_uri = reverse_lazy("accounts:login") + f"?next={current_uri}"
            return HttpResponseClientRedirect(redirect_uri)

    return render(
        request,
        "photolog/_user_follower.html",
        {"is_follower": is_follower, "username": username},
    )


def following_list(request):
    user = request.user
    qs = user.following_set.exclude(pk__in=[user.pk]).select_related("profile")

    return render(
        request, "photolog/user_list.html", {"user_list": qs, "is_follower": True}
    )


def discover_list(request):
    user = request.user
    qs = (
        User.objects.exclude(pk__in=user.following_set.all())
        .exclude(pk__in=[user.pk])
        .select_related("profile")
    )

    return render(
        request, "photolog/user_list.html", {"user_list": qs, "is_follower": False}
    )


# class UserNoteListView(ListView):
#     model = Note
#     template_name = "photolog/user_page.html"

#     def get_queryset(self) -> QuerySet:
#         qs = super().get_queryset()
#         username = self.kwargs["username"]
#         qs = qs.filter(
#             author__username=username, author__is_active=True
#         ).prefetch_related("photo_set", "tags")
#         return qs

#     def get_context_data(self, **kwargs) -> dict:
#         kwargs = super().get_context_data(**kwargs)
#         kwargs["username"] = self.kwargs["username"]
#         return kwargs


class NoteCreateView(LoginRequiredMixin, CreateView):
    model = Note
    form_class = NoteCreateForm
    template_name = "crispy_form.html"
    extra_context = {"form_title": "New Note"}
    # success_url = reverse_lazy("photolog:index")  # TODO: detail 페이지 구현 후 변경

    def form_valid(self, form):
        new_note = form.save(commit=False)
        new_note.author = self.request.user
        new_note.save()

        # 모델에 포함되어있는 필드가 아니므로, 따로 저장 로직 구현
        photo_file_list = form.cleaned_data.get("photos")
        if photo_file_list:
            Photo.create_photos(new_note, photo_file_list)

        response = super().form_valid(form)
        messages.success(self.request, "new note saved! :)")
        return response


class NoteDetailView(DetailView):
    model = Note

    # N+1 문제 발생 : template단에서는 select_related, prefetch_related를 사용할 수 없기 때문에 view로 로직 이동
    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        note = self.object
        context["comment_list"] = note.comment_set.select_related("author__profile")
        return context


# TODO: photos에 대한 처리를 위해 Formset 이용 => CBV보다 FBV가 구현 용이
class NoteUpdateView(LoginRequiredMixin, UpdateView):
    model = Note
    form_class = NoteCreateForm
    template_name = "crispy_form.html"
    extra_context = {"form_title": "Edit Note"}

    # Note.author에 한해서만 수정 가능하도록 queryset 설정
    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(author=self.request.user)
        return qs


@login_required
def note_edit(request, pk):
    note = get_object_or_404(Note, pk=pk, author=request.user)
    photo_qs = note.photo_set.all()

    if request.method == "GET":
        note_form = NoteUpdateForm(instance=note, prefix="note")
        photo_formset = PhotoUpdateFormSet(
            queryset=photo_qs, instance=note, prefix="photos"
        )
    else:
        note_form = NoteUpdateForm(
            data=request.POST, files=request.FILES, instance=note, prefix="note"
        )
        photo_formset = PhotoUpdateFormSet(
            queryset=photo_qs,
            instance=note,
            data=request.POST,
            files=request.FILES,
            prefix="photos",
        )
        if note_form.is_valid() and photo_formset.is_valid():
            saved_note = note_form.save()

            # 새롭게 생성되는 Photo
            photo_file_list = note_form.cleaned_data.get("photos")
            if photo_file_list:
                Photo.create_photos(saved_note, photo_file_list)

            # 기존 Photo 수정
            photo_formset.save()

            messages.success(request, f"note #{saved_note.pk} saved! :)")
            return redirect(saved_note)

    return render(
        request,
        "crispy_form_and_formset.html",
        {
            "form": note_form,
            "form_title": "Note Edit",
            "formset": photo_formset,
            "form_submit_label": "Save",
        },
    )


@method_decorator(login_required_hx, name="dispatch")
class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = "photolog/_comment_form.html"

    # 에러 상황 발생 테스트를 위해 dispatch 메서드 사용
    # def dispatch(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
    #     1 / 0
    #     return super().dispatch(request, *args, **kwargs)

    # form에 request 값 전달을 위해 get_form_kwargs 메서드 재정의
    def get_form_kwargs(self) -> dict:
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs

    # 유효성 검사가 끝나고 나서 호출
    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        comment = form.save(commit=False)
        comment.author = self.request.user
        note_pk = self.kwargs["note_pk"]
        comment.note = get_object_or_404(Note, pk=note_pk)
        comment.save()

        messages.success(self.request, f"note #{note_pk} comment saved :)")

        response = render(self.request, "_messages_as_event.html")

        # "refresh-comment-list" 이벤트를 전달
        response = trigger_client_event(response, "refresh-comment-list")

        return response


class CommentListView(ListView):
    model = Comment
    template_name = "photolog/_comment_list.html"

    def get_queryset(self):
        qs = super().get_queryset()
        note_pk = self.kwargs["note_pk"]
        qs = qs.filter(note__pk=note_pk)
        qs = qs.select_related("author__profile")
        return qs


@method_decorator(login_required_hx, name="dispatch")
class CommentUpdateView(UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = "photolog/_comment_form.html"

    def get_form_kwargs(self) -> dict:
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs

    def get_queryset(self) -> QuerySet:
        qs = super().get_queryset()
        qs = qs.filter(author=self.request.user)
        return qs

    # 유효성 검사가 끝나고 나서 호출
    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        note_pk = self.kwargs["note_pk"]
        form.save()

        messages.success(self.request, f"note #{note_pk} comment saved :)")
        response = render(self.request, "_messages_as_event.html")
        response = trigger_client_event(response, "refresh-comment-list")

        return response


@method_decorator(login_required_hx, name="dispatch")
class CommentDeleteView(DeleteView):
    model = Comment

    def get_queryset(self) -> QuerySet:
        qs = super().get_queryset()
        note_pk = self.kwargs["note_pk"]
        qs = qs.filter(note__pk=note_pk, author=self.request.user)
        return qs

    def form_valid(self, form):
        self.object.delete()

        messages.success(self.request, f"comment deleted :(")

photolog/templates/photolog/_comment_form.html
{% load component_tags crispy_forms_tags partials %}

{% partialdef form %}
  {% crispy form %}
{% endpartialdef %}

{% if request.method == "POST" %}
  {% partial form %}
{% else %}
  {% component 'modal-form' %}
    {% fill 'modal-title' %}
      {% if not form.instance.pk %}new comment{% else %}comment edit{% endif %}
    {% endfill %}
    {% fill 'modal-body' %}
      {% partial form %}
    {% endfill %}
  {% endcomponent %}
  <script>
    (function(){
      const modalEl = document.currentScript.previousElementSibling;
      
      // refresh-comment-list 이벤트를 받으면, modal 숨김
      document.body.addEventListener('refresh-comment-list', () => {
        htmx.trigger(modalEl, "hide")
      });
    })();
  </script>
{% endif %}

photolog/templates/photolog/_comment_list.html
{% load i18n %}

{% for comment in comment_list %}
<div class="d-flex flex-row p-3">
{% if comment.author.profile.avatar %}
    <img src="{{ comment.author.profile.avatar.url }}"
        class="rounded-circle me-3"
        style="width: 60px; height: 60px;"
        alt="{{ comment.author.username }}'s Avatar">
{% endif %}
<div class="w-100">
    <div class="d-flex flex-row align-items-center gap-3">
        <a href="{% url 'photolog:user_page' comment.author.username %}"
            class="text-decoration-none text-black">
            {{ comment.author.username }}</a>
        {% language "en-us" %}
            <span class="text-secondary">{{ note.created_at|timesince }} ago</span>
        {% endlanguage %}
    </div>
    <div>
        {{ comment.message }}
    </div>
    <div class="d-flex flex-row gap-2">
        {% if comment.author == user %}
            <a href="" 
                hx-get="{% url 'photolog:comment_edit' comment.note.pk comment.pk %}"
                hx-target="body"
                hx-swap="beforeend"
                hx-get-with-timestamp
                class="text-primary text-decoration-none">
            edit
            </a>
            <a href=""
                hx-post="{% url 'photolog:comment_delete' comment.note.pk comment.pk %}"
                hx-confirm="Are you sure?"
                hx-target="body"
                hx-swap="beforeend"
                class="text-danger text-decoration-none">
                delete
            </a>
        {% endif %}
      </div>
  </div>
</div>
{% endfor %}

photolog/templates/photolog/_note_list.html
{% load component_tags %}

<div class="container">
  <div class="row">
    {% for note in note_list %}
      {% component "image-overlay" class="col-xl-3 col-lg-4 col-md-6 mt-4" %}
      {% fill 'href' %}{% url 'photolog:note_detail' note.pk %}{% endfill %}
      {% fill "img-src" %}{{ note.photo_set.all.0.image.url }}{% endfill %}
      {% fill "text" %}
              {{ note.title }}<br/>
              <small>by {{ note.author.username }}</small>
              <small class="d-block mt-3 text-muted">
                {% for tag in note.tags.all %}
                    {% if forloop.counter0 < 5 %}
                        #{{ tag.name }}
                    {% endif %}
                {% endfor %}
              </small>
      {% endfill %}
      {% endcomponent %}
    {% endfor %}
  </div>
</div>

photolog/templates/photolog/_user_follower.html
{% if request.user.username != username %}
  {% if is_follower %}
    <div class="mb-2">
      <i class="bi bi-person-check-fill fs-3"></i>
    </div>
    <a href=""
      hx-post="{% url 'photolog:user_follow' username %}"
      hx-target="#follow-container"
      class="btn btn-danger btn-sm">
      unfollow</a>
  {% else %}
    <div class="mb-2">
      <i class="bi bi-person fs-3"></i>
    </div>
    <a href=""
      hx-post="{% url 'photolog:user_follow' username %}"
      hx-target="#follow-container"
      class="btn btn-primary btn-sm">
      follow</a>
  {% endif %}
{% endif %}

photolog/templates/photolog/base.html
{% extends "base.html" %}

{% block content %}
  {% block photolog-content %}
  {% endblock photolog-content %}
{% endblock content %}

photolog/templates/photolog/index.html
{% extends "photolog/base.html" %}
{% load component_tags %}

{% block photolog-content %}
  {% include "photolog/_note_list.html" %}


{% endblock photolog-content %}

photolog/templates/photolog/note_detail.html
{% extends "photolog/base.html" %}
{% load i18n component_tags %}

{% block photolog-content %}
<div class="card">
<div class="card-header">
    <div class="d-flex flex-row gap-2">
        {% if note.author.profile.avatar %}
            <img src="{{ note.author.profile.avatar.url }}"
                class="rounded-circle"
                style="width: 40px; height: 40px;"
                alt="" />
        {% endif %}
        <div class="w-100">
            <div class="d-flex flex-column">
                <a href="{% url 'photolog:user_page' note.author.username %}"
                    class="text-decoration-none text-black"
                >{{ note.author.username }}</a>
                {% language "en-us" %}
                    <span class="text-secondary">{{ note.created_at|timesince }} ago</span>
                {% endlanguage %}
            </div>
        </div>
    </div>
</div>
<div class="card-body">
    <div class="row">
        <div class="col-md-6">
            <h4>{{ note.title }}</h4>
            <div data-hashtag-linkify="{% url 'photolog:index' %}?tag=">
                {{ note.content|linebreaks }}
            </div>
        </div>
        <div class="col-md-6">
            {% component 'carousel' photo_list=note.photo_set.all attr_name="image.url" %}{% endcomponent %}
        </div>
    </div>
</div>
</div>

<div class="my-3">
    <a href="{% url 'photolog:index' %}" class="btn btn-primary">Timeline</a>
    {% if request.user == note.author %}
    <a href="{% url 'photolog:note_edit' note.pk %}" class="btn btn-success">Edit</a>
    {% endif %}
</div>
<a class="btn btn-primary w-100" 
    {% comment %} href="{% url 'photolog:comment_new' note.pk %}" {% endcomment %}
    hx-get="{% url 'photolog:comment_new' note.pk %}"
    hx-with-timestamp
    hx-target="body"
    hx-swap="beforeend" {# body 끝에 추가 #}
    >add comment</a>

    <div class="my-3" id="comment-container">
        {% include 'photolog/_comment_list.html' with user=request.user comment_list=comment_list only %}
    </div>
    <a href="" 
        hx-get="{% url 'photolog:comment_list' note.pk %}"
        hx-get-with-timestamp
        hx-target="#comment-container"
        hx-trigger="click, refresh-comment-list from:body"
        class="btn btn-primary w-100">refresh comment</a>

{% endblock photolog-content %}

photolog/templates/photolog/user_list.html
{% extends "photolog/base.html" %}

{% block photolog-content %}
<div class="row">
  {% for user in user_list %}
      <div class="col-xl-3 col-lg-4 col-md-6 mt-4">
          <div class="card h-100">
              <div class="card-header">
                  <div class="d-flex flex-row align-items-center gap-2">
                      {% if user.profile.avatar %}
                          <img src="{{ user.profile.avatar.url }}"
                                class="rounded-circle"
                                style="width: 32px; height: 32px;"
                                alt="">
                      {% else %}
                          <i class="bi bi-person-circle"
                              style="font-size: 1.6rem;"
                          ></i>
                      {% endif %}
                      <a href="{% url 'photolog:user_page' user.username %}"
                          class="text-black text-decoration-none"
                      >
                          @{{ user.username }}
                      </a>
                  </div>
              </div>
              <div class="card-body">
                  <span class="text-muted">자기 소개가 없어요.{# profile에 자기소개 추가 X #}</span>
              </div>
              <div class="card-footer">
                  <div id="follow-container">
                    {% include "photolog/_user_follower.html" with is_follower=is_follower username=user.username %}
                  </div>
              </div>
          </div>
      </div>
  {% endfor %}
</div>
{% endblock photolog-content %}

photolog/templates/photolog/user_page.html
{% extends "photolog/base.html" %}

{% block photolog-content %}
  <div class="d-flex flex-column align-items-center gap-2 py-5 text-center">
    {% if author.profile.avatar %}
      <img src="{{ author.profile.avatar.url }}" alt="" class="rounded-circle" style="width: 128px; height: 128px;">
    {% endif %}
    <h2>@{{ author.username }}</h2>
    <div id="follow-container">
      <div hx-get="{% url 'photolog:user_follow' author.username %}"
          hx-trigger="load"
          hx-swap="outerHTML"></div>
      </div>
    </div>

  {% include "photolog/_note_list.html" %}
{% endblock photolog-content %}