accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("profile/", views.profile, name="profile"),
    path("profile/edit/", views.ProfileUpdateView.as_view(), name="profile_edit"),
]

blog/urls.py
from django.urls import path, include
from . import views
from . import api
from .api import PostModelViewSet
from rest_framework.routers import DefaultRouter
from django.views.generic import TemplateView


app_name = "blog"

router = DefaultRouter()
router.register(prefix="posts", viewset=PostModelViewSet)


urlpatterns = [
    # path("", TemplateView.as_view(template_name="blog/index.html"), name="index"),
    path("", views.index, name="index"),
    path("whoami/", views.whoami, name="whoami"),
]
urlpatterns_api_v1 = []
urlpatterns_api_v1 += router.urls

# urlpatterns_api_v1 = [
#     path("", api.post_list, name="post_list"),
#     path("<int:pk>/", api.post_detail, name="post_detail"),
#     path("new/", api.post_list, name="post_new"),
#     path("<int:pk>/edit/", api.post_detail, name="post_edit"),
#     path("<int:pk>/delete/", api.post_detail, name="post_delete"),
# ]

urlpatterns += [path("api/", include((urlpatterns_api_v1, "api-v1")))]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static

from django_nextjs.render import render_nextjs_page


# asgi에서는 async 지원
async def root(request):
    return await render_nextjs_page(request)


urlpatterns = [
    path("", root),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("blog/", include("blog.urls")),
    path("", include("photolog.urls")),
    path("", include("core.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if apps.is_installed("debug_toolbar"):
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

core/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = "core"

urlpatterns = [
    # path("", TemplateView.as_view(template_name="root.html"), name="root"),
]

photolog/urls.py
from django.urls import path
from . import views


app_name = "photolog"

urlpatterns = [
    path("", views.index, name="index"),
    path("@<str:username>/", views.user_page, name="user_page"),
    path("@<str:username>/follow/", views.user_follow, name="user_follow"),
    path("user/following/", views.following_list, name="following_list"),
    path("user/discover/", views.discover_list, name="discover_list"),
    path("new/", views.NoteCreateView.as_view(), name="note_new"),
    path("<int:pk>/", views.NoteDetailView.as_view(), name="note_detail"),
    path("<int:pk>/edit/", views.note_edit, name="note_edit"),
    path(
        "<int:note_pk>/comments/", views.CommentListView.as_view(), name="comment_list"
    ),
    path(
        "<int:note_pk>/comment/new/",
        views.CommentCreateView.as_view(),
        name="comment_new",
    ),
    path(
        "<int:note_pk>/comment/<int:pk>/edit/",
        views.CommentUpdateView.as_view(),
        name="comment_edit",
    ),
    path(
        "<int:note_pk>/comment/<int:pk>/delete/",
        views.CommentDeleteView.as_view(),
        name="comment_delete",
    ),
]

core/templates/_crispy_form.html
{# form만 담는 _crispy_form.html #}

{# crispy template 태그에서는 첫번째 인자의 form 인스턴스에서 helper 속성이 있으면 helper를 자동으로 활용 #}  
{# {% crispy form %} #}

{% load crispy_forms_tags %}

<div class="row py-5">
  <div class="col-sm-8 offset-sm-2">
    <div class="card">
        {% if form_title %}
            <div class="card-header">
                {{ form_title }}
            </div>
        {% endif %}
        <div class="card-body">
          {% if form.helper %}
            {% crispy form form.helper %}
          {% else %}
            {% crispy form %}
          {% endif %}  
        </div>
    </div>
  </div>
</div>

core/templates/_crispy_form_and_formset.html
{% load crispy_forms_tags %}

<form {% if form_action %}action="{{ form_action }}"{% endif %}
      method="post"
      {% if form.is_multipart or formset.is_multipart %}enctype="multipart/form-data"{% endif %}
      novalidate
>
    <div class="row py-5">
        <div class="col-sm-8 offset-sm-2">
            <div class="card">
                {% if form_title %}
                    <div class="card-header">
                        {{ form_title }}
                    </div>
                {% endif %}
                <div class="card-body">
                    {% if form %}
                        {% crispy form %}
                    {% endif %}
                    {% if formset %}
                        {% crispy formset %}
                    {% endif %}
                </div>
                <div class="card-footer">
                    <input type="submit" class="btn btn-primary w-100"
                           {% if form_submit_label %}value="{{ form_submit_label }}"{% endif %}
                    />
                </div>
            </div>
        </div>
    </div>
</form>

core/templates/_messages_as_event.html
{% if messages %}
    {% for message in messages %}
        <script>
          (function () {
            const tag = "{{ message.level_tag }}";
            const message = "{{ message }}"
            /* body 요소에 toast-message 이벤트를 보냅니다. */
            htmx.trigger(document.body, 'toast-message', {message: message, tag: tag});
          })();
        </script>
    {% endfor %}
{% endif %}

core/templates/base.html
{% load static component_tags %}

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>myproj</title>
  
  <!-- css -->
  <link rel="stylesheet" href="{% static 'bootstrap/5.3.3/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap-icons/1.11.3/font/bootstrap-icons.min.css' %}">
  {% component_css_dependencies %}
  <!-- css end -->
</head>
{# htmx 요청에서 자동으로 요청 헤더에 csrf token 전송 #}
<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
  
  <!-- header -->
  <nav class="py-2 bg-body-tertiary border-bottom">
    <div class="container d-flex flex-wrap">
      <ul class="nav me-auto">
        <li class="nav-item"><a href="{% url 'photolog:index' %}" class="nav-link link-body-emphasis px-2 active" aria-current="page">Home</a></li>
        <li class="nav-item"><a href="{% url 'photolog:index' %}" class="nav-link link-body-emphasis px-2">Timeline</a></li>
        <li class="nav-item"><a href="{% url 'photolog:note_new' %}" class="nav-link link-body-emphasis px-2">New Note</a></li>
        <li class="nav-item"><a href="{% url 'photolog:following_list' %}" class="nav-link link-body-emphasis px-2">Following</a></li>
        <li class="nav-item"><a href="{% url 'photolog:discover_list' %}" class="nav-link link-body-emphasis px-2">Discover</a></li>
      
      </ul>
      <ul class="nav">
        {% if not user.is_authenticated %}
          {% url 'accounts:login' as login_url %}
          <li class="nav-item"><a href="{{ login_url }}{% if login_url != request.path %}?next={{ request.path }}{% endif %}" class="nav-link link-body-emphasis px-2">Login</a></li>
          <li class="nav-item"><a href="{% url 'accounts:signup' %}?next={{ request.path }}" class="nav-link link-body-emphasis px-2">Sign up</a></li>
        {% else %}
          <li class="nav-item"><a href="{% url 'accounts:profile' %}" class="nav-link link-body-emphasis px-2">Profile</a></li>
          <li class="nav-item"><a href="#" class="nav-link link-body-emphasis px-2" hx-post="{% url 'accounts:logout' %}?next={{ request.path }}" hx-target="body" hx-push-url="true">Logout</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <header class="py-3 mb-4 border-bottom">
    <div class="container d-flex flex-wrap justify-content-center">
      <a href="/" class="d-flex align-items-center mb-3 mb-lg-0 me-lg-auto link-body-emphasis text-decoration-none">
        <span class="fs-4">Proj</span>
      </a>
      <form class="col-12 col-lg-auto mb-3 mb-lg-0" role="search" action="{% url 'photolog:index' %}">
        <input name="query" value="{{ query }}" type="search" class="form-control" placeholder="Search..." aria-label="Search">
      </form>
    </div>
  </header>
  <!-- header end -->

  <!-- main -->
  <main class="py-5">
    <div class="container">
      {% block content %}{% endblock content %}
    </div>
  </main>
  <!-- main end -->

  <!-- footer -->
  <footer class="py-5 text-body-secondary">
    <div class="container">
      &copy; demo
    </div>
  </footer>
  <!-- footer end -->

  <!-- script -->
  {% if debug %}
  <script src="{% static 'htmx/2.0.0/htmx.js' %}"></script>
  {% else %}
  <script src="{% static 'htmx/2.0.0/htmx.min.js' %}"></script>
  {% endif %}
  <script src="{% static 'htmx/ext/hx-get-with-timestamp.js' %}"></script>
  <script src="{% static "bootstrap/5.3.3/js/bootstrap.min.js" %}"></script>
  <script src="{% static "observe-node-insertion.js" %}"></script>
  <script src="{% static "hashtag-linkify.js" %}"></script>
  {% component_js_dependencies %}
  <script src="{% static "toast-messages.js" %}"></script>
  {% include "_messages_as_event.html" %}
  <!-- script end -->

  <script>
    // htmx는 200 이상 400 미만 상태코드 응답만 처리하고
    // 그 외에는 htmx:responseError 발생 => 응답 에러 이벤트를 따로 처리하는 로직 필요
    document.body.addEventListener("htmx:responseError", event => {
      console.error("HTMX 요청 에러:", event.detail);
      const message = event.detail.error;
      const tag = "error"
      htmx.trigger(document.body, "toast-message", { message, tag });
    });

  </script>
  
  {% block script %}{% endblock script %}
</body>
</html>

core/templates/crispy_form.html
{# crispy 라이브러리를 이용해서 공용 폼 템플릿 생성 #}

{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

  {% include "_crispy_form.html" with form=form form_title=form_title %}

{% endblock content %}

core/templates/crispy_form_and_formset.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    {% include "_crispy_form_and_formset.html" with form=form formset=formset form_title=form_title form_submit_label=form_submit_label %}
{% endblock %}

core/templates/nextjs_base.html
{% extends "django_nextjs/document_base.html" %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'bootstrap/5.3.3/css/bootstrap.min.css' %}"/>

    {# <head> 태그 시작 #}
    {{ block.super }}
    {# </head> 태그 끝 #}
{% endblock %}

{% block body %}
    <div class="container">
        <h1>장고 레이아웃 템플릿</h1>

        {# <body> 태그 시작 #}
        {{ block.super }}
        {# </body> 태그 끝 #}

        {# django단에서 내용 추가를 위한 block #}
        {% block django_content %}{% endblock %}
    </div>
{% endblock %}

core/templates/root.html
{% extends "base.html" %}
{% load component_tags %}

{% block content %}

<div>root.html</div>

  {% comment %} {% component "modal-form" %}{% endcomponent %} {% endcomment %}

{% endblock content %}